CREATE UNIQUE INDEX UNIQ_3D4EE408803DB254 ON stranky (url_stranky);
CREATE UNIQUE INDEX UNIQ_nazev_rok ON akce_lokace (nazev, rok);
ALTER TABLE reporty_log_pouziti ADD CONSTRAINT FK_FEAC86E4C6E1AB00 FOREIGN KEY (id_reportu) REFERENCES reporty (id) ON DELETE CASCADE;
ALTER TABLE reporty_log_pouziti ADD CONSTRAINT FK_FEAC86E4D84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
CREATE INDEX IDX_FEAC86E4C6E1AB00 ON reporty_log_pouziti (id_reportu);
CREATE INDEX IDX_FEAC86E4D84E9520 ON reporty_log_pouziti (id_uzivatele);
CREATE INDEX IDX_id_reportu_id_uzivatele ON reporty_log_pouziti (id_reportu, id_uzivatele);
ALTER TABLE akce_seznam ADD CONSTRAINT FK_2EE8EBF0AF219F1D FOREIGN KEY (patri_pod) REFERENCES akce_instance (id_instance) ON DELETE SET NULL;
ALTER TABLE akce_seznam ADD CONSTRAINT FK_2EE8EBF03ACF2B8 FOREIGN KEY (lokace) REFERENCES akce_lokace (id_lokace) ON DELETE SET NULL;
ALTER TABLE akce_seznam ADD CONSTRAINT FK_2EE8EBF0241AA1D FOREIGN KEY (typ) REFERENCES akce_typy (id_typu) ON DELETE RESTRICT;
ALTER TABLE akce_seznam ADD CONSTRAINT FK_2EE8EBF0CEB69E0D FOREIGN KEY (stav) REFERENCES akce_stav (id_stav) ON DELETE RESTRICT;
ALTER TABLE akce_seznam ADD CONSTRAINT FK_2EE8EBF0607A39CF FOREIGN KEY (zamcel) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE SET NULL;
ALTER TABLE akce_seznam ADD CONSTRAINT FK_2EE8EBF0757768BF FOREIGN KEY (popis) REFERENCES texty (id) ON DELETE RESTRICT;
CREATE INDEX IDX_2EE8EBF0AF219F1D ON akce_seznam (patri_pod);
CREATE INDEX IDX_2EE8EBF03ACF2B8 ON akce_seznam (lokace);
CREATE INDEX IDX_2EE8EBF0241AA1D ON akce_seznam (typ);
CREATE INDEX IDX_2EE8EBF0CEB69E0D ON akce_seznam (stav);
CREATE INDEX IDX_2EE8EBF0607A39CF ON akce_seznam (zamcel);
CREATE INDEX IDX_2EE8EBF0757768BF ON akce_seznam (popis);
CREATE INDEX IDX_rok ON akce_seznam (rok);
CREATE UNIQUE INDEX UNIQ_url_akce_rok_typ ON akce_seznam (url_akce, rok, typ);
ALTER TABLE ubytovani ADD CONSTRAINT FK_F483CEC3D84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
CREATE INDEX IDX_F483CEC3D84E9520 ON ubytovani (id_uzivatele);
ALTER TABLE uzivatele_role_podle_rocniku ADD CONSTRAINT FK_9204F263D84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
ALTER TABLE uzivatele_role_podle_rocniku ADD CONSTRAINT FK_9204F263DC499668 FOREIGN KEY (id_role) REFERENCES role_seznam (id_role) ON DELETE CASCADE;
CREATE INDEX IDX_9204F263D84E9520 ON uzivatele_role_podle_rocniku (id_uzivatele);
CREATE INDEX IDX_9204F263DC499668 ON uzivatele_role_podle_rocniku (id_role);
ALTER TABLE google_api_user_tokens ADD CONSTRAINT FK_9A526EB4A76ED395 FOREIGN KEY (user_id) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
CREATE INDEX IDX_9A526EB4A76ED395 ON google_api_user_tokens (user_id);
CREATE UNIQUE INDEX UNIQ_user_id_google_client_id ON google_api_user_tokens (user_id, google_client_id);
ALTER TABLE platby ADD CONSTRAINT FK_4852A679D84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE SET NULL;
ALTER TABLE platby ADD CONSTRAINT FK_4852A67969513658 FOREIGN KEY (provedl) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE RESTRICT;
CREATE INDEX IDX_4852A679D84E9520 ON platby (id_uzivatele);
CREATE INDEX IDX_4852A67969513658 ON platby (provedl);
CREATE INDEX IDX_id_uzivatele_rok ON platby (id_uzivatele, rok);
CREATE UNIQUE INDEX UNIQ_fio_id ON platby (fio_id);
ALTER TABLE kategorie_sjednocenych_tagu ADD CONSTRAINT FK_A82F4189FF2287A1 FOREIGN KEY (id_hlavni_kategorie) REFERENCES kategorie_sjednocenych_tagu (id) ON DELETE CASCADE;
CREATE INDEX IDX_A82F4189FF2287A1 ON kategorie_sjednocenych_tagu (id_hlavni_kategorie);
CREATE UNIQUE INDEX UNIQ_nazev ON kategorie_sjednocenych_tagu (nazev);
ALTER TABLE log_udalosti ADD CONSTRAINT FK_459DF155498E1820 FOREIGN KEY (id_logujiciho) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
CREATE INDEX IDX_459DF155498E1820 ON log_udalosti (id_logujiciho);
CREATE INDEX IDX_metadata ON log_udalosti (metadata);
ALTER TABLE uzivatele_role ADD CONSTRAINT FK_4F909638D84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
ALTER TABLE uzivatele_role ADD CONSTRAINT FK_4F909638DC499668 FOREIGN KEY (id_role) REFERENCES role_seznam (id_role) ON DELETE CASCADE;
ALTER TABLE uzivatele_role ADD CONSTRAINT FK_4F909638AAB26C2 FOREIGN KEY (posadil) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE SET NULL;
CREATE INDEX IDX_4F909638D84E9520 ON uzivatele_role (id_uzivatele);
CREATE INDEX IDX_4F909638DC499668 ON uzivatele_role (id_role);
CREATE INDEX IDX_4F909638AAB26C2 ON uzivatele_role (posadil);
CREATE UNIQUE INDEX UNIQ_id_uzivatele_id_role ON uzivatele_role (id_uzivatele, id_role);
ALTER TABLE akce_typy ADD CONSTRAINT FK_C12F7955DC7C4C42 FOREIGN KEY (stranka_o) REFERENCES stranky (id_stranky) ON DELETE RESTRICT;
CREATE INDEX IDX_C12F7955DC7C4C42 ON akce_typy (stranka_o);
CREATE INDEX IDX_infopult_poznamka ON uzivatele_hodnoty (infopult_poznamka);
CREATE UNIQUE INDEX UNIQ_login_uzivatele ON uzivatele_hodnoty (login_uzivatele);
CREATE UNIQUE INDEX UNIQ_email1_uzivatele ON uzivatele_hodnoty (email1_uzivatele);
ALTER TABLE novinky ADD CONSTRAINT FK_626265713B8BA7C7 FOREIGN KEY (text) REFERENCES texty (id) ON DELETE RESTRICT;
CREATE INDEX IDX_626265713B8BA7C7 ON novinky (text);
CREATE UNIQUE INDEX UNIQ_url ON novinky (url);
ALTER TABLE google_drive_dirs ADD CONSTRAINT FK_9E13BEAFA76ED395 FOREIGN KEY (user_id) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
CREATE INDEX IDX_9E13BEAFA76ED395 ON google_drive_dirs (user_id);
CREATE INDEX IDX_tag ON google_drive_dirs (tag);
CREATE UNIQUE INDEX UNIQ_dir_id ON google_drive_dirs (dir_id);
CREATE UNIQUE INDEX UNIQ_user_and_name ON google_drive_dirs (user_id, original_name);
CREATE INDEX IDX_skupina ON systemove_nastaveni (skupina);
CREATE UNIQUE INDEX UNIQ_klic_rocnik_nastaveni ON systemove_nastaveni (klic, rocnik_nastaveni);
CREATE UNIQUE INDEX UNIQ_nazev_rocnik_nastaveni ON systemove_nastaveni (nazev, rocnik_nastaveni);
ALTER TABLE shop_nakupy ADD CONSTRAINT FK_1A37DD21D84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
ALTER TABLE shop_nakupy ADD CONSTRAINT FK_1A37DD218369B810 FOREIGN KEY (id_objednatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE SET NULL;
ALTER TABLE shop_nakupy ADD CONSTRAINT FK_1A37DD213AB9335E FOREIGN KEY (id_predmetu) REFERENCES shop_predmety (id_predmetu) ON DELETE RESTRICT;
CREATE INDEX IDX_1A37DD21D84E9520 ON shop_nakupy (id_uzivatele);
CREATE INDEX IDX_1A37DD218369B810 ON shop_nakupy (id_objednatele);
CREATE INDEX IDX_1A37DD213AB9335E ON shop_nakupy (id_predmetu);
CREATE INDEX IDX_rok_id_uzivatele ON shop_nakupy (rok, id_uzivatele);
ALTER TABLE akce_import ADD CONSTRAINT FK_D72EE2CDD84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
CREATE INDEX IDX_D72EE2CDD84E9520 ON akce_import (id_uzivatele);
CREATE INDEX IDX_google_sheet_id ON akce_import (google_sheet_id);
ALTER TABLE slevy ADD CONSTRAINT FK_17003B9AD84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
ALTER TABLE slevy ADD CONSTRAINT FK_17003B9A69513658 FOREIGN KEY (provedl) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE SET NULL;
CREATE INDEX IDX_17003B9AD84E9520 ON slevy (id_uzivatele);
CREATE INDEX IDX_17003B9A69513658 ON slevy (provedl);
CREATE UNIQUE INDEX UNIQ_kod_predmetu_model_rok ON shop_predmety (kod_predmetu, model_rok);
ALTER TABLE hromadne_akce_log ADD CONSTRAINT FK_E0A93D8A69513658 FOREIGN KEY (provedl) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE SET NULL;
CREATE INDEX IDX_E0A93D8A69513658 ON hromadne_akce_log (provedl);
CREATE INDEX IDX_akce ON hromadne_akce_log (akce);
CREATE INDEX IDX_typ_role ON role_seznam (typ_role);
CREATE INDEX IDX_vyznam_role ON role_seznam (vyznam_role);
CREATE UNIQUE INDEX UNIQ_kod_role ON role_seznam (kod_role);
CREATE UNIQUE INDEX UNIQ_nazev_role ON role_seznam (nazev_role);
ALTER TABLE akce_prihlaseni_log ADD CONSTRAINT FK_947919F21E74DA0A FOREIGN KEY (id_akce) REFERENCES akce_seznam (id_akce) ON DELETE CASCADE;
ALTER TABLE akce_prihlaseni_log ADD CONSTRAINT FK_947919F2D84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
ALTER TABLE akce_prihlaseni_log ADD CONSTRAINT FK_947919F2E2649593 FOREIGN KEY (id_zmenil) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE SET NULL;
CREATE INDEX IDX_947919F21E74DA0A ON akce_prihlaseni_log (id_akce);
CREATE INDEX IDX_947919F2D84E9520 ON akce_prihlaseni_log (id_uzivatele);
CREATE INDEX IDX_947919F2E2649593 ON akce_prihlaseni_log (id_zmenil);
CREATE INDEX IDX_typ ON akce_prihlaseni_log (typ);
CREATE INDEX IDX_zdroj_zmeny ON akce_prihlaseni_log (zdroj_zmeny);
CREATE UNIQUE INDEX UNIQ_id_akce_id_uzivatele ON akce_prihlaseni (id_akce, id_uzivatele);
ALTER TABLE akce_prihlaseni ADD CONSTRAINT FK_7B7E722B1E74DA0A FOREIGN KEY (id_akce) REFERENCES akce_seznam (id_akce);
ALTER TABLE akce_prihlaseni ADD CONSTRAINT FK_7B7E722BD84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele);
ALTER TABLE akce_prihlaseni ADD CONSTRAINT FK_7B7E722B55D06BC9 FOREIGN KEY (id_stavu_prihlaseni) REFERENCES akce_prihlaseni_stavy (id_stavu_prihlaseni);
CREATE INDEX IDX_7B7E722B1E74DA0A ON akce_prihlaseni (id_akce);
CREATE INDEX IDX_7B7E722BD84E9520 ON akce_prihlaseni (id_uzivatele);
CREATE INDEX IDX_7B7E722B55D06BC9 ON akce_prihlaseni (id_stavu_prihlaseni);
ALTER TABLE medailonky ADD CONSTRAINT FK_55E27418D84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
ALTER TABLE akce_stavy_log ADD CONSTRAINT FK_195FCE481E74DA0A FOREIGN KEY (id_akce) REFERENCES akce_seznam (id_akce) ON DELETE CASCADE;
ALTER TABLE akce_stavy_log ADD CONSTRAINT FK_195FCE484596820F FOREIGN KEY (id_stav) REFERENCES akce_stav (id_stav) ON DELETE CASCADE;
CREATE INDEX IDX_195FCE481E74DA0A ON akce_stavy_log (id_akce);
CREATE INDEX IDX_195FCE484596820F ON akce_stavy_log (id_stav);
ALTER TABLE uzivatele_url ADD CONSTRAINT FK_BA2D6079D84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
CREATE UNIQUE INDEX UNIQ_BA2D6079F47645AE ON uzivatele_url (url);
CREATE INDEX IDX_BA2D6079D84E9520 ON uzivatele_url (id_uzivatele);
ALTER TABLE systemove_nastaveni_log ADD CONSTRAINT FK_8F9C0959D84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE SET NULL;
ALTER TABLE systemove_nastaveni_log ADD CONSTRAINT FK_8F9C0959C8E5E058 FOREIGN KEY (id_nastaveni) REFERENCES systemove_nastaveni (id_nastaveni) ON DELETE CASCADE;
CREATE INDEX IDX_8F9C0959D84E9520 ON systemove_nastaveni_log (id_uzivatele);
CREATE INDEX IDX_8F9C0959C8E5E058 ON systemove_nastaveni_log (id_nastaveni);
CREATE UNIQUE INDEX UNIQ_skript ON reporty (skript);
ALTER TABLE role_texty_podle_uzivatele ADD CONSTRAINT FK_D4CCA4DFD84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
CREATE INDEX IDX_D4CCA4DFD84E9520 ON role_texty_podle_uzivatele (id_uzivatele);
CREATE UNIQUE INDEX UNIQ_id_uzivatele_vyznam_role ON role_texty_podle_uzivatele (id_uzivatele, vyznam_role);
ALTER TABLE shop_nakupy_zrusene ADD CONSTRAINT FK_EB331F2FD84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
ALTER TABLE shop_nakupy_zrusene ADD CONSTRAINT FK_EB331F2F3AB9335E FOREIGN KEY (id_predmetu) REFERENCES shop_predmety (id_predmetu) ON DELETE RESTRICT;
CREATE INDEX IDX_EB331F2FD84E9520 ON shop_nakupy_zrusene (id_uzivatele);
CREATE INDEX IDX_EB331F2F3AB9335E ON shop_nakupy_zrusene (id_predmetu);
CREATE INDEX IDX_datum_zruseni ON shop_nakupy_zrusene (datum_zruseni);
CREATE INDEX IDX_zdroj_zruseni ON shop_nakupy_zrusene (zdroj_zruseni);
CREATE INDEX IDX_email ON newsletter_prihlaseni_log (email);
ALTER TABLE akce_sjednocene_tagy ADD CONSTRAINT FK_714E29671E74DA0A FOREIGN KEY (id_akce) REFERENCES akce_seznam (id_akce) ON DELETE CASCADE;
ALTER TABLE akce_sjednocene_tagy ADD CONSTRAINT FK_714E2967DFF2D11 FOREIGN KEY (id_tagu) REFERENCES sjednocene_tagy (id) ON DELETE CASCADE;
CREATE INDEX IDX_714E29671E74DA0A ON akce_sjednocene_tagy (id_akce);
CREATE INDEX IDX_714E2967DFF2D11 ON akce_sjednocene_tagy (id_tagu);
ALTER TABLE prava_role ADD CONSTRAINT FK_57A9921ADC499668 FOREIGN KEY (id_role) REFERENCES role_seznam (id_role) ON DELETE CASCADE;
ALTER TABLE prava_role ADD CONSTRAINT FK_57A9921A1A86105C FOREIGN KEY (id_prava) REFERENCES r_prava_soupis (id_prava) ON DELETE CASCADE;
CREATE INDEX IDX_57A9921ADC499668 ON prava_role (id_role);
CREATE INDEX IDX_57A9921A1A86105C ON prava_role (id_prava);
ALTER TABLE sjednocene_tagy ADD CONSTRAINT FK_EEE57AA8FFC91574 FOREIGN KEY (id_kategorie_tagu) REFERENCES kategorie_sjednocenych_tagu (id);
CREATE INDEX IDX_EEE57AA8FFC91574 ON sjednocene_tagy (id_kategorie_tagu);
CREATE UNIQUE INDEX UNIQ_nazev ON sjednocene_tagy (nazev);
ALTER TABLE mutex ADD CONSTRAINT FK_EECDB22FCF5C09F0 FOREIGN KEY (zamknul) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE SET NULL;
CREATE UNIQUE INDEX UNIQ_EECDB22FEC2A7D56 ON mutex (klic);
CREATE INDEX IDX_EECDB22FCF5C09F0 ON mutex (zamknul);
CREATE UNIQUE INDEX UNIQ_email ON newsletter_prihlaseni (email);
ALTER TABLE obchod_bunky ADD CONSTRAINT FK_2DA00FBEE5BF0939 FOREIGN KEY (mrizka_id) REFERENCES obchod_mrizky (id) ON DELETE CASCADE;
CREATE INDEX IDX_2DA00FBEE5BF0939 ON obchod_bunky (mrizka_id);
CREATE UNIQUE INDEX UNIQ_nazev ON akce_stav (nazev);
ALTER TABLE akce_instance ADD CONSTRAINT FK_F1D05242895FCA4C FOREIGN KEY (id_hlavni_akce) REFERENCES akce_seznam (id_akce) ON DELETE CASCADE;
CREATE INDEX IDX_F1D05242895FCA4C ON akce_instance (id_hlavni_akce);
ALTER TABLE akce_prihlaseni_spec ADD CONSTRAINT FK_78A8F4401E74DA0A FOREIGN KEY (id_akce) REFERENCES akce_seznam (id_akce);
ALTER TABLE akce_prihlaseni_spec ADD CONSTRAINT FK_78A8F440D84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele);
ALTER TABLE akce_prihlaseni_spec ADD CONSTRAINT FK_78A8F44055D06BC9 FOREIGN KEY (id_stavu_prihlaseni) REFERENCES akce_prihlaseni_stavy (id_stavu_prihlaseni);
CREATE INDEX IDX_78A8F4401E74DA0A ON akce_prihlaseni_spec (id_akce);
CREATE INDEX IDX_78A8F440D84E9520 ON akce_prihlaseni_spec (id_uzivatele);
CREATE INDEX IDX_78A8F44055D06BC9 ON akce_prihlaseni_spec (id_stavu_prihlaseni);
CREATE UNIQUE INDEX UNIQ_id_akce_id_uzivatele ON akce_prihlaseni_spec (id_akce, id_uzivatele);
ALTER TABLE uzivatele_role_log ADD CONSTRAINT FK_9977B328D84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
ALTER TABLE uzivatele_role_log ADD CONSTRAINT FK_9977B328DC499668 FOREIGN KEY (id_role) REFERENCES role_seznam (id_role) ON DELETE CASCADE;
ALTER TABLE uzivatele_role_log ADD CONSTRAINT FK_9977B328E2649593 FOREIGN KEY (id_zmenil) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE SET NULL;
CREATE INDEX IDX_9977B328D84E9520 ON uzivatele_role_log (id_uzivatele);
CREATE INDEX IDX_9977B328DC499668 ON uzivatele_role_log (id_role);
CREATE INDEX IDX_9977B328E2649593 ON uzivatele_role_log (id_zmenil);
ALTER TABLE akce_organizatori ADD CONSTRAINT FK_F44FC74E1E74DA0A FOREIGN KEY (id_akce) REFERENCES akce_seznam (id_akce) ON DELETE CASCADE;
ALTER TABLE akce_organizatori ADD CONSTRAINT FK_F44FC74ED84E9520 FOREIGN KEY (id_uzivatele) REFERENCES uzivatele_hodnoty (id_uzivatele) ON DELETE CASCADE;
CREATE INDEX IDX_F44FC74E1E74DA0A ON akce_organizatori (id_akce);
CREATE INDEX IDX_F44FC74ED84E9520 ON akce_organizatori (id_uzivatele);
