---
- name: Ensure sftp group exists
  ansible.builtin.group:
    name: "{{ sftp_group }}"
    state: present

- name: Enable sftp only for user group
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/sftp.conf
    content: |
      Match Group {{ sftp_group }}
          ChrootDirectory %h
          X11Forwarding no
          AllowTCPForwarding no
          ForceCommand internal-sftp
          #AuthorizedKeysFile /srv/www/authorized_keys/%u.keys
    mode: "0644"
  notify: Restart sshd

- name: Create sftp user
  ansible.builtin.user:
    user: "{{ user.name }}"
    home: "{{ sftp_root }}/{{ user.name }}"
    group: "{{ sftp_group }}"
    umask: "0022"
    shell: /usr/sbin/nologin
    create_home: false
    state: present
  loop: "{{ sftp_users | d([]) }}"
  loop_control:
    loop_var: user
