<?php

/** @var \Godric\DbMigrations\Migration $this */

$this->q(<<<SQL
UPDATE akce_seznam SET lokace = NULL WHERE TRUE;

TRUNCATE TABLE akce_lokace;

ALTER TABLE akce_lokace
    MODIFY COLUMN rok INT DEFAULT 0;

INSERT INTO akce_lokace(nazev, dvere, poznamka, poradi)
VALUES
('RPG 1 - 3L pokoj','Budova B, dveře č. 21','3L pokoj',1),
('RPG 2','Budova B, dveře č. 20','',2),
('RPG 3','Budova B, dveře č. 19','',3),
('RPG 4','Budova B, dveře č. 18','',4),
('RPG 5','Budova B, dveře č. 17','',5),
('RPG 6','Budova B, dveře č. 16','',6),
('RPG 7 - 3L pokoj','Budova B, dveře č. 15','3L pokoj',7),
('RPG 8 - 3L pokoj','Budova B, dveře č. 13','3L pokoj',8),
('RPG 9','Budova B, dveře č. 12','',9),
('RPG 10','Budova B, dveře č. 11','',10),
('RPG 11','Budova B, dveře č. 10','',11),
('RPG 12','Budova B, dveře č. 9','',12),
('RPG 13','Budova B, dveře č. 8','',13),
('RPG 14 - 3L pokoj','Budova B, dveře č. 121','3L pokoj',14),
('RPG 15 - 3L pokoj','Budova B, dveře č. 115','3L pokoj',15),
('RPG 16 - 3L pokoj','Budova B, dveře č. 113','3L pokoj',16),
('RPG 17 - klubovna','Budova B, dveře č. 209','TV místnost',17),
('RPG 18 - klubovna','Budova B, dveře č. 309','TV místnost',18),
('RPG 19 - klubovna','Budova A, 3. patro naproti schodům','TV místnost',19),
('LKD 1','Budova B, dveře č. 120','',20),
('LKD 2','Budova B, dveře č. 119','',21),
('LKD 3','Budova B, dveře č. 118','',22),
('LKD 4','Budova B, dveře č. 117','',23),
('LKD 5','Budova B, dveře č. 116','',24),
('LKD 6','Budova B, dveře č. 112','',25),
('LKD 7','Budova B, dveře č. 111','',26),
('EPIC 1 - klubovna','Budova A, 1. patro naproti schodům','',27),
('EPIC 2 - klubovna','Budova A, 2. patro naproti schodům','',28),
('EPIC 3','Waldorf třída','bude upřesněno',29),
('EPIC 4','Waldorf třída','bude upřesněno',30),
('EPIC 5','Waldorf třída','bude upřesněno',31),
('EPIC 6','Waldorf třída','bude upřesněno',32),
('EPIC 7','Waldorf třída','bude upřesněno',33),
('LARP 1 - dvoupokoj', '', '',34),
('LARP 2 - snídárna','Budova B, dveře č. 27','',35),
('LARP 3 - W. družina','Waldorf družina','',36),
('LARP 4 - W. altán','Waldorf altán','',37),
('LARP 5 - DM knihovna', '', '',38),
('LARP 6 - DDM 42','DDM 42','',39),
('LARP 7 - DDM 36','DDM 36','',40),
('LARP 8 - DDM hudebna','DDM hudebna','',41),
('DESK 1 - předsálí kina','KD, 1. patro, předsálí up ','',42),
('DESK 2 - prosklený sál','KD, 1. patro, prosklený sál','',43),
('DESK 3 - 2. malá vpravo','KD, 1. patro, druhá vpravo','',44),
('DESK 4 - 1. malá vpravo ','KD, 1. patro, první vpravo','',45),
('DESK 5 - dlouhá vlevo','KD, 1. patro, vlevo','',46),
('DESK 6 - foyer','KD, 1. patro, foyer','',47),
('DESK 7 - sál ','KD, 1. patro, taneční sál','',48),
('DESK 8 - pódium','KD, 1. patro, pódium','',49),
('BONUS 1 - zahrada C','Zahrada C','',50),
('BONUS 2 - zahrada A/B','Zahrada A/B','',51),
('BONUS 3 - venku na GC','Venku na GC','',52),
('BONUS 4 - DDM sál','DDM Sál','',53),
('BONUS 5 - tělocvična','Tělocvična','',54),
('mDrD 1','Waldorf třída','Bude upřesněno',55),
('mDrD 2','Waldorf třída','Bude upřesněno',56),
('mDrD 3','Waldorf třída','Bude upřesněno',57),
('mDrD 4','Waldorf třída','Bude upřesněno',58),
('mDrD 5','Waldorf třída','Bude upřesněno',59),
('mDrD 6','Waldorf třída','Bude upřesněno',60),
('mDrD 7','Waldorf třída','Bude upřesněno',61),
('Přednáškovka','Budova A, přízemí, dveře č. 18','Sborovna',62),
('Prog 1 - kino','KD, 1. patro, kinosál','',63),
('Prog 2 - předsálí DOWN','KD, přízemí, předsálí down','',64),
('Prog 3 - mimo GC','Mimo GC','',65),
('Prog 4 - rezerva', '', '',66),
('Prog 5 - rezerva', '', '',67),
('Prog 6 - rezerva', '', '',68),
('Prog 7 - rezerva', '', '',69),
('Prog 8 - rezerva', '', '',70),
('Provoz 1 - infopult','Infopult','',71),
('Provoz 2 - štáb','Budova B, 1. patro naproti schodům','',72),
('Provoz 3 - sklad','Sklad','',73),
('Provoz 4 - zahrada KD','Zahrada KD','',74),
('Provoz 5 - ostatní','Ostatní','',75);
SQL
);
