<?php

/** @var \Godric\DbMigrations\Migration $this */

$this->q(<<<SQL
UPDATE akce_seznam SET lokace = NULL WHERE TRUE;

TRUNCATE TABLE akce_lokace;

INSERT INTO akce_lokace(nazev, dvere, poznamka, poradi)
VALUES
('RPG 1','Budova C, dveře č. 1','Pokoj 3L',1),
('RPG 2','Budova C, dveře č. 38','Pokoj 3L',2),
('RPG 3','Budova C, dveře č. 37','Pokoj 3L',3),
('RPG 4','Budova C, dveře č. 36','Pokoj 3L',4),
('RPG 5','Budova C, dveře č. 35','Pokoj 3L',5),
('RPG 6','Budova C, dveře č. 34','Pokoj 3L',6),
('RPG 7','Budova C, dveře č. 33','Pokoj 3L',7),
('RPG 8','Budova C, dveře č. 32','Pokoj 3L',8),
('RPG 9','Budova C, dveře č. 30','Pokoj 3L',9),
('RPG 10','Budova C, dveře č. 22','Pokoj 3L',10),
('RPG 11','Budova C, dveře č. 21','Pokoj 3L',11),
('RPG 12','Budova C, dveře č. 20','Pokoj 3L',12),
('RPG 13','Budova C, dveře č. 19','Pokoj 3L',13),
('RPG 14','Budova C, dveře č. 18','Pokoj 3L',14),
('RPG 15','Budova C, dveře č. 17','Pokoj 3L',15),
('RPG 16','Budova C, dveře č. 16','Pokoj 3L',16),
('RPG 17','Budova C, dveře č. 15','Pokoj 3L',17),
('RPG 18','Budova C, dveře č. 119','Pokoj 3L',18),
('RPG 19','Budova C, dveře č. 118','Pokoj 3L',19),
('RPG 20','Budova C, dveře č. 117','Pokoj 3L',20),
('RPG 21','Budova C, dveře č. 116','Pokoj 3L',21),
('LKD 1','Budova C, dveře č. 129','Pokoj 3L',22),
('LKD 2','Budova C, dveře č. 127','Pokoj 3L',23),
('LKD 3','Budova C, dveře č. 126','Pokoj 3L',24),
('LKD 4','Budova C, dveře č. 125','Pokoj 3L',25),
('LKD 5','Budova C, dveře č. 123','Pokoj 3L',26),
('LKD 6','Budova C, dveře č. 121','Pokoj 3L',27),
('LKD 7','Budova C, dveře č. 120','Pokoj 3L',28),
('EPIC 1 - sál p0','Budova C, vchod z jídelny','Tělocvična vedle jídelny',29),
('EPIC 2 - klubovna 0p','Budova C, dveře č. 11','Prosklená klubovna',30),
('EPIC 3','Budova C, dveře č. 12','Pokoj 3L',31),
('EPIC 4 - TV místnost 0p','Budova C, dveře č. 13','TV Místnost na C',32),
('EPIC 5 - klubovna 1p','Budova C, dveře č. 103','Prosklená klubovna',33),
('EPIC 6 - klubovna 1p','Budova C, dveře č. 110','Prosklená klubovna',34),
('EPIC 7 - TV místnost 1p','Budova C, dveře č. 111','TV Místnost na C',35),
('EPIC 8','Budova C, dveře č. 112','Pokoj 3L',36),
('EPIC 9','Budova C, dveře č. 113','Pokoj 3L',37),
('EPIC 10','Budova C, dveře č. 114','Pokoj 3L',38),
('EPIC 11','Budova C, dveře č. 115','Pokoj 3L',39),
('EPIC 12 - klubovna 2p','Budova C, dveře č. 210','Prosklená klubovna',40),
('EPIC 13','Budova C, dveře č. 211','Pokoj 3L',41),
('LARP 1 - dvoupokoj','Budova C, dveře č. 310+311','Dvojmístnost',42),
('LARP 2 - snídárna','Budova B, dveře č. 27','Studentský klub',43),
('LARP 3 - W. družina','Waldorf družina','Samostatná budova',44),
('LARP 4 - W. altán','Waldorf altán','Zahrada družiny',45),
('LARP 5 - DDM 42','DDM 42, 1. patro', '',46),
('LARP 6 - DDM 36','DDM 36, 1. patro','Třída',47),
('LARP 7 - DDM hudebna','DDM 12, 2. patro','Hudebna',48),
('LARP 8 - DM knihovna','Budova B, suterén','Po schodech dolů vpravo, dveře vpravo',49),
('LARP 9 - 1L pokoj','Budova C, dveře č. 308','Pokoj 1L',50),
('DESK 1 - předsálí kina','KD, 1. patro, předsálí up', '',51),
('DESK 2 - prosklený sál','KD, 1. patro, prosklený sál', '',52),
('DESK 3 - 2. malá vpravo','KD, 1. patro, druhá vpravo', '',53),
('DESK 4 - 1. malá vpravo','KD, 1. patro, první vpravo', '',54),
('DESK 5 - dlouhá vlevo','KD, 1. patro, vlevo', '',55),
('DESK 6 - foyer','KD, 1. patro, foyer', '',56),
('DESK 7 - sál','KD, 1. patro, taneční sál', '',57),
('DESK 8 - pódium','KD, 1. patro, pódium', '',58),
('BONUS 1 - zahrada C','Zahrada C', '',59),
('BONUS 2 - zahrada A/B','Zahrada A/B', '',60),
('BONUS 3 - venku na GC','Venku na GC', '',61),
('BONUS 4 - DDM sál','DDM Sál','Přízemí',62),
('BONUS 5 - tělocvična','Tělocvična','Záložní tělocvična Waldorf',63),
('mDrD 1','Budova C, dveře č. 100','Pokoj 3L',64),
('mDrD 2','Budova C, dveře č. 135','Pokoj 3L',65),
('mDrD 3','Budova C, dveře č. 134','Pokoj 3L',66),
('mDrD 4','Budova C, dveře č. 102','Pokoj 3L',67),
('mDrD 5','Budova C, dveře č. 133','Pokoj 3L',68),
('mDrD 6','Budova C, dveře č. 132','Pokoj 3L',69),
('mDrD 7','Budova C, dveře č. 131','Pokoj 3L',70),
('mDrD 8','Budova C, dveře č. 130','Pokoj 3L',71),
('WG 1 - klubovna 2p','Budova C, dveře č. 203','Prosklená klubovna',72),
('WG 2 - klubovna 3p','Budova C, dveře č. 303','Prosklená klubovna',73),
('Přednáškovka','Budova C, suterén, hudební klub', '',74),
('Prog 1 - kino','KD, 1. patro, kinosál', '',75),
('Prog 2 - předsálí DOWN','KD, přízemí, předsálí down', '',76),
('Prog 3 - mimo GC','Mimo GC', '',77),
('Prog 4 - bunkr I','Budova C, suterén, bunkr I', '',78),
('Prog 5 - bunkr B','Budova C, suterén, bunkr B', '',79),
('Prog 6 - bunkr C','Budova C, suterén, bunkr C', '',80),
('Prog 7 - bunkr D+E','Budova C, suterén, bunkr D+E', '',81),
('Prog 8 - sborovna','Budova A, dveře č. 18', '',82),
('Prog 9 - rezerva', '', '',83),
('Prog 10 - rezerva', '', '',84),
('Prog 11 - rezerva', '', '',85),
('Prog 12 - rezerva', '', '',86),
('Provoz 1 - infopult','Infopult', '',87),
('Provoz 2 - štáb','Budova C, dveře č. 28', '',88),
('Provoz 3 - sklad','Sklad', '',89),
('Provoz 4 - zahrada KD','Zahrada KD', '',90),
('Provoz 5 - ostatní','Ostatní', '',91);
SQL,
);
