-- Revert ON UPDATE CASCADE back to RESTRICT for FKs that don't reference uzivatele_hodnoty.id_uzivatele.
-- These were incorrectly set by a blanket migration. Only uzivatele_hodnoty.id_uzivatele FKs need ON UPDATE CASCADE
-- (for data anonymization in AnonymizovanaDatabaze).

ALTER TABLE akce_instance
    DROP FOREIGN KEY IF EXISTS FK_F1D05242895FCA4C;
ALTER TABLE akce_instance
    ADD CONSTRAINT FK_F1D05242895FCA4C FOREIGN KEY (id_hlavni_akce) REFERENCES akce_seznam (id_akce) ON DELETE CASCADE;

ALTER TABLE akce_lokace
    DROP FOREIGN KEY IF EXISTS FK_49CCDE681E74DA0A;
ALTER TABLE akce_lokace
    ADD CONSTRAINT FK_49CCDE681E74DA0A FOREIGN KEY (id_akce) REFERENCES akce_seznam (id_akce) ON DELETE CASCADE;

ALTER TABLE akce_lokace
    DROP FOREIGN KEY IF EXISTS FK_49CCDE68259B4755;
ALTER TABLE akce_lokace
    ADD CONSTRAINT FK_49CCDE68259B4755 FOREIGN KEY (id_lokace) REFERENCES lokace (id_lokace) ON DELETE CASCADE;

ALTER TABLE akce_organizatori
    DROP FOREIGN KEY IF EXISTS FK_F44FC74E1E74DA0A;
ALTER TABLE akce_organizatori
    ADD CONSTRAINT FK_F44FC74E1E74DA0A FOREIGN KEY (id_akce) REFERENCES akce_seznam (id_akce) ON DELETE CASCADE;

ALTER TABLE akce_prihlaseni
    DROP FOREIGN KEY IF EXISTS FK_7B7E722B1E74DA0A;
ALTER TABLE akce_prihlaseni
    ADD CONSTRAINT FK_7B7E722B1E74DA0A FOREIGN KEY (id_akce) REFERENCES akce_seznam (id_akce) ON DELETE RESTRICT;

ALTER TABLE akce_prihlaseni
    DROP FOREIGN KEY IF EXISTS FK_7B7E722B55D06BC9;
ALTER TABLE akce_prihlaseni
    ADD CONSTRAINT FK_7B7E722B55D06BC9 FOREIGN KEY (id_stavu_prihlaseni) REFERENCES akce_prihlaseni_stavy (id_stavu_prihlaseni) ON DELETE RESTRICT;

ALTER TABLE akce_prihlaseni_log
    DROP FOREIGN KEY IF EXISTS FK_947919F21E74DA0A;
ALTER TABLE akce_prihlaseni_log
    ADD CONSTRAINT FK_947919F21E74DA0A FOREIGN KEY (id_akce) REFERENCES akce_seznam (id_akce) ON DELETE CASCADE;

ALTER TABLE akce_prihlaseni_spec
    DROP FOREIGN KEY IF EXISTS FK_78A8F4401E74DA0A;
ALTER TABLE akce_prihlaseni_spec
    ADD CONSTRAINT FK_78A8F4401E74DA0A FOREIGN KEY (id_akce) REFERENCES akce_seznam (id_akce) ON DELETE RESTRICT;

ALTER TABLE akce_prihlaseni_spec
    DROP FOREIGN KEY IF EXISTS FK_78A8F44055D06BC9;
ALTER TABLE akce_prihlaseni_spec
    ADD CONSTRAINT FK_78A8F44055D06BC9 FOREIGN KEY (id_stavu_prihlaseni) REFERENCES akce_prihlaseni_stavy (id_stavu_prihlaseni) ON DELETE RESTRICT;

ALTER TABLE akce_sjednocene_tagy
    DROP FOREIGN KEY IF EXISTS FK_714E29671E74DA0A;
ALTER TABLE akce_sjednocene_tagy
    ADD CONSTRAINT FK_714E29671E74DA0A FOREIGN KEY (id_akce) REFERENCES akce_seznam (id_akce) ON DELETE CASCADE;

ALTER TABLE akce_sjednocene_tagy
    DROP FOREIGN KEY IF EXISTS FK_714E2967DFF2D11;
ALTER TABLE akce_sjednocene_tagy
    ADD CONSTRAINT FK_714E2967DFF2D11 FOREIGN KEY (id_tagu) REFERENCES sjednocene_tagy (id) ON DELETE CASCADE;

ALTER TABLE akce_stavy_log
    DROP FOREIGN KEY IF EXISTS FK_195FCE481E74DA0A;
ALTER TABLE akce_stavy_log
    ADD CONSTRAINT FK_195FCE481E74DA0A FOREIGN KEY (id_akce) REFERENCES akce_seznam (id_akce) ON DELETE CASCADE;

ALTER TABLE akce_typy
    DROP FOREIGN KEY IF EXISTS FK_C12F7955DC7C4C42;
ALTER TABLE akce_typy
    ADD CONSTRAINT FK_C12F7955DC7C4C42 FOREIGN KEY (stranka_o) REFERENCES stranky (id_stranky) ON DELETE RESTRICT;

ALTER TABLE kategorie_sjednocenych_tagu
    DROP FOREIGN KEY IF EXISTS FK_A82F4189FF2287A1;
ALTER TABLE kategorie_sjednocenych_tagu
    ADD CONSTRAINT FK_A82F4189FF2287A1 FOREIGN KEY (id_hlavni_kategorie) REFERENCES kategorie_sjednocenych_tagu (id) ON DELETE CASCADE;

ALTER TABLE shop_nakupy
    DROP FOREIGN KEY IF EXISTS FK_1A37DD213AB9335E;
ALTER TABLE shop_nakupy
    ADD CONSTRAINT FK_1A37DD213AB9335E FOREIGN KEY (id_predmetu) REFERENCES shop_predmety (id_predmetu) ON DELETE RESTRICT;

ALTER TABLE shop_nakupy_zrusene
    DROP FOREIGN KEY IF EXISTS FK_EB331F2F3AB9335E;
ALTER TABLE shop_nakupy_zrusene
    ADD CONSTRAINT FK_EB331F2F3AB9335E FOREIGN KEY (id_predmetu) REFERENCES shop_predmety (id_predmetu) ON DELETE RESTRICT;

ALTER TABLE systemove_nastaveni_log
    DROP FOREIGN KEY IF EXISTS FK_8F9C0959C8E5E058;
ALTER TABLE systemove_nastaveni_log
    ADD CONSTRAINT FK_8F9C0959C8E5E058 FOREIGN KEY (id_nastaveni) REFERENCES systemove_nastaveni (id_nastaveni) ON DELETE CASCADE;

ALTER TABLE uzivatele_role
    DROP FOREIGN KEY IF EXISTS FK_4F909638DC499668;
ALTER TABLE uzivatele_role
    ADD CONSTRAINT FK_4F909638DC499668 FOREIGN KEY (id_role) REFERENCES role_seznam (id_role) ON DELETE CASCADE;

ALTER TABLE uzivatele_role_podle_rocniku
    DROP FOREIGN KEY IF EXISTS FK_9204F263DC499668;
ALTER TABLE uzivatele_role_podle_rocniku
    ADD CONSTRAINT FK_9204F263DC499668 FOREIGN KEY (id_role) REFERENCES role_seznam (id_role) ON DELETE CASCADE;

ALTER TABLE reporty_log_pouziti
    DROP FOREIGN KEY IF EXISTS FK_FEAC86E4C6E1AB00;
ALTER TABLE reporty_log_pouziti
    ADD CONSTRAINT FK_FEAC86E4C6E1AB00 FOREIGN KEY (id_reportu) REFERENCES reporty (id) ON DELETE CASCADE;
ALTER TABLE akce_seznam
    DROP FOREIGN KEY IF EXISTS FK_2EE8EBF09E0F2899;
ALTER TABLE akce_seznam
    DROP FOREIGN KEY IF EXISTS FK_2EE8EBF0241AA1D;
ALTER TABLE akce_seznam
    DROP FOREIGN KEY IF EXISTS FK_2EE8EBF0AF219F1D;
ALTER TABLE akce_seznam
    DROP FOREIGN KEY IF EXISTS FK_2EE8EBF0CEB69E0D;

ALTER TABLE akce_seznam
    ADD CONSTRAINT FK_2EE8EBF0241AA1D FOREIGN KEY (typ) REFERENCES akce_typy (id_typu) ON DELETE RESTRICT;
ALTER TABLE akce_seznam
    ADD CONSTRAINT FK_2EE8EBF0AF219F1D FOREIGN KEY (patri_pod) REFERENCES akce_instance (id_instance) ON DELETE SET NULL;
ALTER TABLE akce_seznam
    ADD CONSTRAINT FK_2EE8EBF0CEB69E0D FOREIGN KEY (stav) REFERENCES akce_stav (id_stav) ON DELETE RESTRICT;
ALTER TABLE akce_stavy_log
    DROP FOREIGN KEY IF EXISTS FK_195FCE484596820F;
ALTER TABLE akce_stavy_log
    ADD CONSTRAINT FK_195FCE484596820F FOREIGN KEY (id_stav) REFERENCES akce_stav (id_stav) ON DELETE CASCADE;
ALTER TABLE prava_role
    DROP FOREIGN KEY IF EXISTS FK_57A9921ADC499668;
ALTER TABLE prava_role
    DROP FOREIGN KEY IF EXISTS FK_57A9921A1A86105C;
ALTER TABLE prava_role
    ADD CONSTRAINT FK_57A9921ADC499668 FOREIGN KEY (id_role) REFERENCES role_seznam (id_role) ON DELETE CASCADE;
ALTER TABLE prava_role
    ADD CONSTRAINT FK_57A9921A1A86105C FOREIGN KEY (id_prava) REFERENCES r_prava_soupis (id_prava) ON DELETE CASCADE;
ALTER TABLE sjednocene_tagy
    DROP FOREIGN KEY IF EXISTS FK_EEE57AA8FFC91574;
ALTER TABLE sjednocene_tagy
    ADD CONSTRAINT FK_EEE57AA8FFC91574 FOREIGN KEY (id_kategorie_tagu) REFERENCES kategorie_sjednocenych_tagu (id);
ALTER TABLE obchod_bunky
    DROP FOREIGN KEY IF EXISTS FK_2DA00FBEE5BF0939;
ALTER TABLE obchod_bunky
    ADD CONSTRAINT FK_2DA00FBEE5BF0939 FOREIGN KEY (mrizka_id) REFERENCES obchod_mrizky (id) ON DELETE CASCADE;
ALTER TABLE uzivatele_role_log
    DROP FOREIGN KEY IF EXISTS FK_9977B328DC499668;
ALTER TABLE uzivatele_role_log
    ADD CONSTRAINT FK_9977B328DC499668 FOREIGN KEY (id_role) REFERENCES role_seznam (id_role) ON DELETE CASCADE;
