#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "${DIR}/_tty.sh"

mkdir -p "$HOME/.composer/cache"

if [ "$(docker compose ps web | grep --count Up)" -gt 0 ]; then
	docker_compose_exec \
		--workdir="${GAMECON_CONTAINER_DIR}" \
		--user=www-data \
		web composer "$@"
else
	docker_compose_run \
		--workdir="${GAMECON_CONTAINER_DIR}" \
		--user=www-data \
		web composer "$@"
fi
