#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$DIR")"
PROJECT_DIR="$(basename "$PROJECT_ROOT")"

source "${DIR}/_tty.sh"

mkdir -p "$HOME/.composer/cache"

if [ "$(docker compose ps phpnginx | grep --count Up)" -gt 0 ]; then
	docker_compose_exec \
		--workdir="/var/www/html/${PROJECT_DIR}" \
		--user=www-data \
		web composer "$@"
else
	docker_compose_run \
    --workdir="/var/www/html/${PROJECT_DIR}" \
		--user=www-data \
		web composer "$@"
fi
