#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "${DIR}/_tty.sh"

if [ "$(docker compose ps web | grep --count Up)" -gt 0 ]; then
	docker_compose_exec \
		--workdir="${GAMECON_CONTAINER_DIR}/ui" \
		--user=www-data \
		web yarn "$@"
else
	docker_compose_run \
		--workdir="${GAMECON_CONTAINER_DIR}/ui" \
		--user=www-data \
		web yarn "$@"
fi
