---
name: Create external backup

# yamllint disable-line rule:truthy
on:
  schedule:
    # Run every day at 10am
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  create-backup:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: backup
    env:
      RCLONE_HOST: ${{ secrets.RCLONE_HOST }}
      RCLONE_USER: ${{ secrets.RCLONE_USER }}
      RCLONE_PASS: ${{ secrets.RCLONE_PASS }}
      BORG_SSHKEY: ${{ secrets.BORG_SSHKEY }}
      BORG_REPO: ${{ secrets.BORG_REPO }}
      BORG_PASSPHRASE: ${{ secrets.BORG_PASSPHRASE }}
      FTP_DIR: ostra
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites and create initial configuration
        run: |
          sudo apt-get update
          sudo apt-get install borgbackup
          sudo pip install borgmatic
          curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          unzip rclone-current-linux-amd64.zip
          sudo cp rclone-*-linux-amd64/rclone /usr/local/bin
          sudo chmod +x /usr/local/bin/rclone
          rclone config create --non-interactive gamecon ftp \
            host=$RCLONE_HOST \
            user=$RCLONE_USER \
            pass=$RCLONE_PASS \
            explicit_tls=true
          echo "$BORG_SSHKEY" > sshkey
          chmod 0600 sshkey
      - name: Start backup process
        run: >-
          borgmatic create
          --config borgmatic.yaml
          --verbosity 1
